### PR TITLE
Updated Ischemic stroke cause model states and transitions diagrams.

### PR DESCRIPTION
**Pull request by SantoniS**
@collijk reviewed the 'Cause model' and 'Transitions' diagrams and requested updates. This PR is for those updates of simplifying the diagrams.

### CODE REVIEW

**Comment by SantoniS** [comment]
I updated the diagrams to be SVG file formats.

**Comment by NathanielBlairStahn** [comment]
@SantoniS @collijk Is it necessary to have two separate diagrams, or can we just have one cause model diagram with both states and transitions (i.e. the one labeled transition diagram here)?

**Comment by collijk** [comment]
Yeah, we just want your "transitions" diagram

**Comment by SantoniS** [comment]
> @SantoniS @collijk Is it necessary to have two separate diagrams, or can we just have one cause model diagram with both states and transitions (i.e. the one labeled transition diagram here)?

I made this update so 'Cause Model Diagram' includes both states and transitions. Thanks!

**Pull request merged**
