### PR TITLE
Added cause hierarchy, restrictions, and data description tables to diabetes mellitus model.

### PR DESCRIPTION
**Pull request by SantoniS**

### CODE REVIEW

**Comment by SantoniS** [comment]
I need to include remission and update the cause model and data tables.

**Comment by NathanielBlairStahn** [comment]
Small detail: If this is a PAF-of-1 cause, it should go in the "Risk-Attributable Cause Models" section:

`vivarium_research/docs/source/models/gbd2017/risk_attributable_causes`

**Comment by SantoniS** [comment]
@NathanielBlairStahn  It is a PAF of one cause so I moved it to that folder. Please let me know if I did something incorrectly! Also, I updated the data transitions table to include remission. I also removed 'overall DM' as a cause in the model diagram.

**Comment by NathanielBlairStahn** [comment]
> @NathanielBlairStahn It is a PAF of one cause so I moved it to that folder. Please let me know if I did something incorrectly! Also, I updated the data transitions table to include remission. I also removed 'overall DM' as a cause in the model diagram.

Looks good to me.

**Pull request merged**
