### PR TITLE
ssh required to push to github now, I think

### PR DESCRIPTION
**Pull request by aflaxman**

### CODE REVIEW

**Review by albrja — APPROVED** [review]

**Comment by NathanielBlairStahn** [comment]
Not if you use a personal access token:

- https://stackoverflow.com/questions/67077837/in-what-ways-is-an-ssh-key-different-from-tokens-for-git-authentication#:~:text=While%20SSH%20keys%20can%20be,recommends%20tokens%20over%20SSH%20keys
- https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token

I have a personal access token for my laptop, but I use SSH from the cluster because I wasn't sure how to get tokens to work on the cluster.

**Comment by zmbc** [comment]
I use HTTPS; for the cluster I have a token that I keep in my home directory with permissions so only I can read it.

**Comment by aflaxman** [comment]
Will it make things easier or harder if we steer people towards this approach?  If it doesn't make things easier, I'll leave the docs as they are.

**Comment by NathanielBlairStahn** [comment]
> Will it make things easier or harder if we steer people towards this approach? If it doesn't make things easier, I'll leave the docs as they are.

I think either way, the current documentation is now incomplete because you can't just type in your password to access github. If we want these instructions to be truly useful, we would need to add instructions for creating and using either a token or an SSH key (or both).

**Comment by aflaxman** [comment]
> I think either way, the current documentation is now incomplete because you can't just type in your password to access github. If we want these instructions to be truly useful, we would need to add instructions for creating and using either a token or an SSH key (or both).

How about you give your approval and I merge this for now, but we also note that we should add additional instructions in the future?

**Review by NathanielBlairStahn — APPROVED** [review]

**Pull request merged**
