### PR TITLE
[data] maternal anemia intervention

### PR DESCRIPTION
**Pull request by yongqx**

### CODE REVIEW

**Review by aflaxman — APPROVED** [review]

**Comment by alibow** [comment]
Generally, the equations written out from that google doc are calculations of how the population mean hemoglobin level will change assuming 100% intervention coverage, but this might not be how we implement it for a vivarium simulation. The equations would be good validation criteria if we asked for population mean hemoglobin stratified by target population as a simulation output. However, it might be good in a subsequent PR to indicate how we would model the intervention effects at the simulant level for a vivarium simulation rather than at the population level as we did for the initial maternal anemia project. I am approving for now, but let me know if you have any questions on what I mean!

**Review by alibow — APPROVED** [review]

**Comment by alibow** [comment]
Also, in the assumptions and limitations section, it would be good to note why we are taking an average of those two values for the effect size of IV iron (average of maximum and additive effect) so we don't get confused again.

**Comment by alibow** [comment]
Something else to note for subsequent PRs is that the post-DFS intervention hemoglobin level should be used to determine eligibility for IV iron (hgb < 10 g/dL) rather than the pre-DFS intervention hemoglobin level (again, let me know if this is unclear)

**Comment by yongqx** [comment]
> Generally, the equations written out from that google doc are calculations of how the population mean hemoglobin level will change assuming 100% intervention coverage, but this might not be how we implement it for a vivarium simulation. The equations would be good validation criteria if we asked for population mean hemoglobin stratified by target population as a simulation output. However, it might be good in a subsequent PR to indicate how we would model the intervention effects at the simulant level for a vivarium simulation rather than at the population level as we did for the initial maternal anemia project. I am approving for now, but let me know if you have any questions on what I mean!

Thanks for noting that!

**Pull request merged**
