### PR TITLE
Diabetes model: Updated the State and Transitions data tables, added vivarium modeling strategy, and validation criteria.

### PR DESCRIPTION
**Pull request by SantoniS**
I'll also add information on Fasting Plasma Glucose in this PR. But adding at a later commit.

### CODE REVIEW

**Comment by SantoniS** [comment]
@yongqx  Are you available to review this PR? Thank you! I modeled the validation criteria from LTBI.

**Comment by SantoniS** [comment]
I've copy + pasted this from Slack, if it's better to centralize here:
I have done the data validation of:
1. the sum of incidence of sequelae = the incidence of Diabetes Mellitus
2. the sum of prevalence of sequelae = the prevalence of Diabetes Mellitus
3. CSMR of diabetes mellitus = EMR * Prevalence

**Comment by yongqx** [comment]
> I've copy + pasted this from Slack, if it's better to centralize here:
> I have done the data validation of:
> 
> 1. the sum of incidence of sequelae = the incidence of Diabetes Mellitus
> 2. the sum of prevalence of sequelae = the prevalence of Diabetes Mellitus
> 3. CSMR of diabetes mellitus = EMR * Prevalence

All good! Have you ever looked into YLDs due to Diabetes Mellitus? (YLDs = disability weight * timespan)

**Comment by SantoniS** [comment]
> > I've copy + pasted this from Slack, if it's better to centralize here:
> > I have done the data validation of:
> > 
> > 1. the sum of incidence of sequelae = the incidence of Diabetes Mellitus
> > 2. the sum of prevalence of sequelae = the prevalence of Diabetes Mellitus
> > 3. CSMR of diabetes mellitus = EMR * Prevalence
> 
> All good! Have you ever looked into YLDs due to Diabetes Mellitus? (YLDs = disability weight * timespan)

I have not looked at YLDs due to DM yet but I can do this! Great idea. We are not including YLDs in the data inputs but I can see why it is important to validate before implementing the model, to make note of where possible inconsistencies are ahead of reviewing model outputs.

**Pull request merged**
