### PR TITLE
fix labeling typos for wasting treatment efficacy

### PR DESCRIPTION
**Pull request by alibow**

### CODE REVIEW

**Comment by NathanielBlairStahn** [comment]
@alibow What happened here? SAM and MAM were switched?

**Review by aflaxman — APPROVED** [review]

**Review by rmudambi — APPROVED** [review]

**Comment by alibow** [comment]
> @alibow What happened here? SAM and MAM were switched?

Yes, I accidentally switched them when I reformatted the documentation from Nicole's previous tables. I think that Rajan had probably already implemented them correctly before I made the mistake, is that right, @rmudambi?

**Comment by rmudambi** [comment]
Yes, it's implemented correctly.

**Comment by alibow** [comment]
> Yes, it's implemented correctly.

Woo, thanks!!!

**Pull request merged**
