### PR TITLE
1,000 draws of hemoglobin on maternal disorders PAFs

### PR DESCRIPTION
**Pull request by alibow**

### CODE REVIEW

**Review by aflaxman — APPROVED** [review]

**Comment by aflaxman** [comment]
I made a plot, does this look like you expected
image

**Comment by alibow** [comment]
> I made a plot, does this look like you expected image

Are the colors age groups? Yeah, this is basically what I was expecting

**Comment by alibow** [comment]
> > I made a plot, does this look like you expected image
> 
> Are the colors age groups? Yeah, this is basically what I was expecting

It looks like your PAFs go negative though? I don't think I have any negative PAFs. @aflaxman 
image

**Comment by aflaxman** [comment]
Yeah, the colors are age groups.  the blue one that is a little away from the pack on the left is age_group_id 8.

**Comment by aflaxman** [comment]
That is an artifact of the KDE smoothing algorithm. I tried to get the developer to fix it, but he didn't want to https://github.com/mwaskom/seaborn/issues/525

**Comment by alibow** [comment]
Yeah, I'm not suprised by age group ID 8 being different from the rest because it's often

**Review by plinds — APPROVED** [review]

**Pull request merged**
