### PR TITLE
Switch from ssh to https in contributing instructions

### PR DESCRIPTION
**Pull request by NathanielBlairStahn**
Edit instructions in `README.rst` to suggest cloning the repo using `https` rather than `ssh`, as that's GitHub's recommended method and doesn't require the user to set up an SSH key.

### CODE REVIEW

**Comment by aflaxman** [comment]
Is this really what GitHub recommends now?

**Comment by zmbc** [comment]
I think GitHub has gone back and forth at least 5 times on whether or not HTTPS is the preferred method; right now their documentation doesn't state a preference. But I do think the majority of us use HTTPS and it is easier to set up in my opinion (creating a PAT in the GitHub interface vs. creating an SSH key on the command line).

**Comment by aflaxman** [comment]
> the majority of us use HTTPS and it is easier to set up in my opinion (creating a PAT in the GitHub interface vs. creating an SSH key on the command line).

Ok, as long as this is what you are finding easier these days, I have no problem with changing the docs.

**Review by aflaxman — APPROVED** [review]

**Review by zmbc — APPROVED** [review]

**Comment by NathanielBlairStahn** [comment]
> > the majority of us use HTTPS and it is easier to set up in my opinion (creating a PAT in the GitHub interface vs. creating an SSH key on the command line).
> 
> Ok, as long as this is what you are finding easier these days, I have no problem with changing the docs.

I agree -- I find the GitHub Personal Access Token easier than SSH as well. I can easily add the token to macOS Keychain on my laptop, and on the cluster I think I set up GitHub CLI so that I never have to do anything except update the token when it expires.

@pletale FYI for when you're cloning the repo, and @SylLutze FYI when you're updating the documentation on how to get started with all the computer stuff. We should probably add documentation and links about how to set up a GitHub personal access token and set up GitHub CLI to make it easy to access GitHub. Let me or @zmbc know if you have any questions.

**Pull request merged**
