### PR TITLE
Added cause hierarchy to hemolytic disease/neonatal jaundice

### PR DESCRIPTION
**Pull request by beatrixkh**
I included all the children of "neonatal disorders" because there are few enough that they fit, and because we're thinking about all of them. I can remove if we would prefer.

I also wasn't sure how to represent the sequelae, as there are 42. What I currently have is inaccurate, as there aren't actually {mild, moderate, severe} \times {all subsets of {motor impairment, cognitive impairment, epilepsy, blindness}}. Some of those combinations are missing, though that is very close to describing 41 of the 42 sequelae.

### CODE REVIEW

**Comment by collijk** [comment]
I only see 15 sequelae in the gbd mapping.  Where did you find the sequelae list?

**Comment by beatrixkh** [comment]
eek 😬 . this is perhaps the moment when i need to learn how to use gbd_mapping; I was using get_sequela_metadata from shared functions.

**Comment by collijk** [comment]
The gbd_mapping was built using get_sequela_metadata, so they should agree with each other.  Are you sure you were looking at round 5 (GBD 2017) and not the current round?

**Comment by beatrixkh** [comment]
@collijk I used get_sequela_metadata(sequela_set_id = 2, gbd_round_id = 5)

**Comment by beatrixkh** [comment]
(and when i pull the "sequela_set" id table, it looks like sequela_set_id=2, sequela_set_name=GBD Computation Sequela hierarchy used by COMO for sequela aggregation" is the only entry in the table)

**Comment by beatrixkh** [comment]
oh oops! i had duplicates because it was listing different reis. when i subset to unique, though, i have 16 (not 15)

**Comment by collijk** [comment]
This is the list I have
```
['moderate_motor_plus_cognitive_impairment_with_blindness_due_to_hemolytic_disease_and_other_neonatal_jaundice',
 'moderate_motor_plus_cognitive_impairment_with_blindness_and_epilepsy_due_to_hemolytic_disease_and_other_neonatal_jaundice',
 'moderate_motor_plus_cognitive_impairment_with_epilepsy_due_to_hemolytic_disease_and_other_neonatal_jaundice',
 'severe_motor_plus_cognitive_impairment_with_blindness_due_to_hemolytic_disease_and_other_neonatal_jaundice',
 'severe_motor_plus_cognitive_impairment_with_blindness_and_epilepsy_due_to_hemolytic_disease_and_other_neonatal_jaundice',
 'severe_motor_plus_cognitive_impairment_with_epilepsy_due_to_hemolytic_disease_and_other_neonatal_jaundice',
 'moderate_motor_impairment_due_to_hemolytic_disease_and_other_neonatal_jaundice',
 'moderate_motor_impairment_with_blindness_due_to_hemolytic_disease_and_other_neonatal_jaundice',
 'moderate_motor_impairment_with_blindness_and_epilepsy_due_to_hemolytic_disease_and_other_neonatal_jaundice',
 'moderate_motor_impairment_with_epilepsy_due_to_hemolytic_disease_and_other_neonatal_jaundice',
 'severe_motor_impairment_severe_due_to_hemolytic_disease_and_other_neonatal_jaundice',
 'severe_motor_impairment_with_blindness_due_to_hemolytic_disease_and_other_neonatal_jaundice',
 'severe_motor_impairment_with_blindness_and_epilepsy_due_to_hemolytic_disease_and_other_neonatal_jaundice',
 'severe_motor_impairment_with_epilepsy_due_to_hemolytic_disease_and_other_neonatal_jaundice',
 'extreme_hyperbilirubinemia_due_to_hemolytic_disease_and_other_neonatal_jaundice_without_kernicterus']

```

**Comment by beatrixkh** [comment]
OH oops---this was me being careless. Mine also included '6470;                                                                             Hemolytic disease and other neonatal jaundice', which it oughn't to have. I'll push the correction.

**Comment by collijk** [comment]
Good news!  I was worried that the GBD databases had changed on me.

**Comment by NathanielBlairStahn** [comment]
> I included all the children of "neonatal disorders" because there are few enough that they fit, and because we're thinking about all of them. I can remove if we would prefer.

I like including all the neonatal causes in the hierarchy, since we will usually be modeling them together in the same model. But it would look better if they were all lined up horizontally and two didn't drop below. Is that possible, or does it make the diagram too big?

**Comment by beatrixkh** [comment]
I thought it would @NathanielBlairStahn , but tried it and it seems fine.

**Comment by NathanielBlairStahn** [comment]
> I thought it would @NathanielBlairStahn , but tried it and it seems fine.

Yeah, I like this better, @beatrixkh ! A couple more comments:

1. I would vote for ordering the neonatal causes in order of their cause id, and then we can use the same diagram for all the neonatal causes, just change the sequelae.
2. What does your notation P{...} mean in the sequela list?

**Comment by beatrixkh** [comment]
Yes, can definitely reorder by cause_id. As for the P{...}---this is what I was commenting on at the beginning of this PR---I was meaning to indicate "all subsets of", but that's not actually accurate, so was hoping for feedback/other ideas on how to represent those 14 sequelae (listed above by james) without typing them all out @NathanielBlairStahn

**Comment by NathanielBlairStahn** [comment]
Ahh, P for "power set" - got it 😃 (I usually use 2^X for all subsets of X, but that's unimportant - whatever notation you use, you should just explain it somewhere).

I don't know if there is a good way to precisely specify the sequelae. I spent way too much time figuring out how to count which combinations show up in the 85 sequelae for neural tube defects.  I finally figured it out (I think), but does it actually matter?  Probably not.

For hemolytic disease, the 14 sequelae besides "extreme hyperbilirubinemia" are all 16 combinations of
{moderate, severe} x {motor impairment} x 2^{cognitive impairment, blindness, epilepsy}
(2 x 1 x 8 = 16)
EXCEPT for the two combinations of motor_plus_cognitive_impairment _without_ blindness or epilepsy:
{moderate, severe} x {motor impairment} x {cognitive impairment}
(2 x 1 x 1 = 2)
So there you go. I don't know if that's helpful.

Maybe we can just say:
"14 sequelae of the form {moderate, severe} x (various combinations of {motor impairment, cognitive impairment, epilepsy, blindness})"
or something like that.

**Pull request merged**
