### PR TITLE
iv iron model I.3 validation tracking

### PR DESCRIPTION
**Pull request by alibow**

### CODE REVIEW

**Review by aflaxman — APPROVED** [review]
I sent an outlook invite to discuss tomorrow

**Comment by alibow** [comment]
> I sent an outlook invite to discuss tomorrow

@aflaxman I don't think I got an invite, but I believe we are planning on staying on the call and discussing with the software engineers after their standup tomorrow morning.

**Comment by aflaxman** [comment]
Oops, I forgot to hit send.  But staying on the line after the engineer standup tomorrow works, too.

**Review by mattkappel — APPROVED** [review]
I created [MIC-3011](https://jira.ihme.washington.edu/browse/MIC-3011) to track the issues we SWEs will immediately tackle. This excludes the age group issue and anemia (for now).

**Pull request merged**
